[server]
enableStaticServing = true

[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Regular.otf"
style="normal"
weight=400
[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Bold.otf"
style="normal"
weight=700
[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Light.otf"
style="normal"
weight=400
[[theme.fontFaces]]
family="StabilGrotesk"
url="app/static/StabilGrotesk-Black.otf"
style="normal"
weight=700

[theme]
font="StabilGrotesk"